### ISSUE TITLE
Intel GMA graphics?

### ISSUE THREAD

**Issue by casper** [yantis/docker-dynamic-video#1]
Would this work with Intel i915 GMA graphics too? This is what my lspci is reporting:

 > 00:02.0 VGA compatible controller: Intel Corporation 82G965 Integrated Graphics  Controller (rev 02)

This page seems to indicate it's included in the mesa library. so perhaps it works out of the box?   
https://wiki.archlinux.org/index.php/intel_graphics

Is there some easy way to verify if it's working?

**Comment by yantis** [comment]
It should. You can try one of these:
https://github.com/yantis/docker-virtualgl
https://github.com/yantis/docker-wine

Though it has been a while since I updated these. I mostly put them up so people might find some value in their own projects. It isn't something I actively maintain but they might work.

**Comment by casper** [comment]
Hmm. Ok I installed docker-virtualgl. It almost works, but not quite. I run your container like this:

```
docker run --privileged --rm -ti -v /tmp/.X11-unix:/tmp/.X11-unix:ro -u docker yantis/virtualgl bash
```

And then in the container I get this:

```
[docker@9a6d0e7601d0 /]$ vglrun glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  72 (X_PutImage)
  Serial number of failed request:  41
  Current serial number in output stream:  60
```

Running `xterm` works fine. But glxspheres only flashes the window once, and then it exists with the above error. Maybe the i965 driver isn't there after all?

**Comment by casper** [comment]
Never mind. Seems I need to run the whole thing as root inside the container. Now I get another error, but I think that's a bug in my host kernel:

```
intel_do_flush_locked failed: Invalid argument
```

Will continue to investigate. If I figure it out I'll update it here.

**Comment by casper** [comment]
Ok. I got it to work. 

1) To get around the Intel bug:     
    Add `Option "AccelMethod" "uxa"` to `xorg.conf`

2) To run X inside the docker container:
     Install `xf86-video-intel` (`pacman -S xf86-video-intel`)
